- hosts: master
  become: true
  roles:
    - oracle-java
    - init
    - wildfly
    - master
    - driver
    - driver-master

- hosts: slave
  become: true
  roles:
    - oracle-java
    - init
    - wildfly
    - slave
    - driver
