- name: Download wildfly 11
  get_url:
    url: http://download.jboss.org/wildfly/11.0.0.Final/wildfly-11.0.0.Final.zip
    dest: /opt

- name: unzip wildfly
  unarchive:
    src: /opt/wildfly-11.0.0.Final.zip
    dest: /opt
    remote_src: yes

- name: utente wildfly
  user:
    name: wildfly
    shell: /bin/bash
    system: yes

- name: permessi cartella wildfly
  file:
    path: /opt/wildfly-11.0.0.Final
    owner: wildfly
    group: wildfly
    recurse: yes
