- name: Configurazione host-slave.xml
  template:
    src: host-slave.file
    dest: /opt/wildfly-11.0.0.Final/domain/configuration/host-slave.xml
    owner: wildfly
    group: wildfly
- replace:
    path: /opt/wildfly-11.0.0.Final/domain/configuration/host-slave.xml
    regexp: "IPMASTER"
    replace: "{{hostvars[item]['ansible_default_ipv4']['address']}}"
  with_items:
    - "{{ groups['master'] }}"
