- name: spostare init-d in /opt/wildfly-11../bin
  command: cp /opt/wildfly-11.0.0.Final/docs/contrib/scripts/init.d /opt/wildfly-11.0.0.Final/bin

- name: Configurazione init.d
  template:
    src: init.d
    dest: /opt/wildfly-11.0.0.Final/bin/init.d/wildfly-init-redhat.sh
    owner: wildfly
    group: wildfly

- name: reload daemon
  systemd: daemon_reload=yes
